(() => {
  const $ = (id) => document.getElementById(id);
  sessionStorage.setItem("dispatch_entry_mode_v1", "desktop");
  const state = { language: sessionStorage.getItem("dispatch_language") === "en" ? "en" : "zh", roles: {}, accounts: [], mode: "roles", selectedRole: "", selectedAccount: "" };
  const texts = {
    "车辆调度控制台": "Vehicle Dispatch Console", "权限管理": "Permission settings", "先设置角色默认权限，再为单个账号做独立覆盖": "Set role defaults first, then override access for individual accounts.", "账号管理": "Account management", "桌面调度台": "Desktop console", "退出登录": "Sign out", "角色默认权限": "Role defaults", "个人覆盖": "Individual overrides", "角色默认": "Role defaults", "修改角色后，使用该角色且没有个人覆盖的账号会采用新默认值。": "Accounts using this role without a personal override will use the new defaults.", "选择一个角色": "Select a role", "从左侧选择角色，编辑该角色的默认权限。": "Select a role on the left to edit its default permissions.", "恢复系统默认": "Restore system defaults", "恢复角色默认": "Restore role defaults", "保存角色权限": "Save role permissions", "保存个人权限": "Save individual permissions", "正在读取角色…": "Loading roles…", "正在读取账号…": "Loading accounts…", "请选择左侧角色。": "Select a role from the left.", "请选择左侧账号。": "Select an account from the left.", "角色权限已保存。": "Role permissions saved.", "个人权限已保存。": "Individual permissions saved.", "保存失败。": "Save failed.", "加载角色失败。": "Unable to load roles.", "项权限": "permissions", "继承角色默认": "Role defaults", "已单独覆盖": "Custom override", "正在保存权限…": "Saving permissions…", "已恢复系统默认，请点击保存角色权限。": "System defaults restored. Click save to apply.", "个人权限已恢复为角色默认。": "Individual permissions restored to the role defaults.", "修改后仅影响继承角色默认值的账号": "Only accounts inheriting this role default are affected.", "该账号已覆盖角色默认权限": "This account overrides the role defaults.", "该账号当前继承角色默认权限": "This account currently inherits the role defaults.", "移动调度": "Mobile dispatch", "任务访问": "Task access", "车辆与车况": "Vehicles and condition", "桌面与数据": "Desktop and data", "系统管理": "System administration",
    "进入移动调度": "Open mobile dispatch", "创建出发任务": "Create departure task", "编辑自己的任务": "Edit own tasks", "出发登记": "Submit departure", "中转登记": "Submit transfer", "返回登记": "Submit return", "上传任务照片": "Upload task photos", "预约车辆": "Book vehicles", "跨部门车辆": "Cross-department vehicles", "查看自己的任务": "View own tasks", "查看全部任务": "View all tasks", "编辑全部任务": "Edit all tasks", "审批车辆预约": "Approve vehicle bookings", "删除/取消任务": "Delete or cancel tasks", "车辆档案管理": "Manage vehicle records", "车辆照片管理": "Manage vehicle photos", "保养与保修": "Manage maintenance and warranty", "刷新 Tracker": "Refresh Tracker", "桌面调度台": "Open desktop console", "出行记录": "View trip history", "Tracker 历史": "View Tracker history", "同步调度": "Dispatch sync", "飞书照片同步": "Manage Lark photo sync", "部门通知设置": "Manage department notifications", "账号权限管理": "Manage account permissions",
    "允许进入手机调度页面并读取基础选项。": "Allow access to mobile dispatch and its basic options.", "可查看并选择其他部门的可调度车辆。": "View and select dispatchable vehicles from other departments.", "可新建一条出发调度任务。": "Create a new departure dispatch task.", "只可修改自己作为驾驶人的任务。": "Edit only tasks where this user is the driver.", "提交车辆出发登记并进入执行中。": "Submit the vehicle departure check and start execution.", "登记任务中转地点。": "Record a transfer location for a departed task.", "登记返程路线、里程和车况。": "Record return route, mileage and vehicle condition.", "上传出发或返程车辆照片。": "Upload departure or return vehicle photos.", "发起车辆预约申请。": "Create a vehicle booking request.", "读取自己创建或作为驾驶人的任务。": "Read tasks created by or assigned to this user.", "读取所有调度任务和部门任务。": "Read all dispatch and department tasks.", "修改其他人员的调度任务。": "Edit dispatch tasks belonging to other users.", "同意或拒绝车辆预约。": "Approve or reject vehicle booking requests.", "删除任务或在无法删除时取消归档。": "Delete tasks or cancel-archive them when deletion is unavailable.", "维护车辆基本资料、状态和档案。": "Manage vehicle profile, status and records.", "上传和维护车辆原图及附件。": "Upload and maintain vehicle originals and attachments.", "记录保养、保修单和下次保养计划。": "Record maintenance, warranty files and next service plans.", "发起 Tracker 数据刷新。": "Queue a Tracker data refresh.", "进入桌面调度台。": "Open the desktop operations console.", "查看出行记录。": "View trip records and filters.", "查看车辆 Tracker 历史。": "View historical Tracker records.", "手动执行调度同步。": "Run dispatch synchronization manually.", "连接拥有 Base 权限的管理员并同步车辆照片。": "Connect a Base administrator and sync vehicle photos.", "编辑部门出发、返程和预约通知目标。": "Edit department targets for departure, return and booking notices.", "编辑账号、角色、部门和权限。": "Edit accounts, roles, departments and permissions."
  };
  Object.assign(texts, { "返回桌面调度台": "Back to desktop console" });
  const roleLabels = { dispatcher: "调度员", scheduler: "排程员", fleet_manager: "车队管理员", admin: "管理员" };
  const roleDefaults = {
    dispatcher: ["mobile_dispatch", "view_own_tasks", "create_dispatch", "edit_own_dispatch", "submit_departure", "submit_transfer", "submit_return", "submit_photos", "book_vehicle", "view_all_vehicles"],
    scheduler: ["mobile_dispatch", "view_own_tasks", "view_all_tasks", "create_dispatch", "edit_own_dispatch", "edit_all_dispatch", "submit_departure", "submit_transfer", "submit_return", "submit_photos", "book_vehicle", "approve_bookings", "desktop_console", "view_history", "view_tracker_history", "sync_dispatch", "delete_dispatch", "view_all_vehicles"],
    fleet_manager: ["mobile_dispatch", "view_own_tasks", "view_all_tasks", "create_dispatch", "edit_own_dispatch", "edit_all_dispatch", "submit_departure", "submit_transfer", "submit_return", "submit_photos", "book_vehicle", "desktop_console", "view_history", "view_tracker_history", "view_all_vehicles", "manage_vehicles", "manage_vehicle_photos", "manage_maintenance", "refresh_tracker", "manage_photo_sync"],
    admin: ["mobile_dispatch", "view_own_tasks", "view_all_tasks", "create_dispatch", "edit_own_dispatch", "edit_all_dispatch", "submit_departure", "submit_transfer", "submit_return", "submit_photos", "book_vehicle", "approve_bookings", "desktop_console", "view_history", "view_tracker_history", "sync_dispatch", "delete_dispatch", "view_all_vehicles", "manage_vehicles", "manage_vehicle_photos", "manage_maintenance", "refresh_tracker", "manage_photo_sync", "manage_accounts", "manage_notifications"]
  };
  const groups = [
    { label: "移动调度", permissions: [["mobile_dispatch", "进入移动调度", "允许进入手机调度页面并读取基础选项。"], ["view_all_vehicles", "跨部门车辆", "可查看并选择其他部门的可调度车辆。"], ["create_dispatch", "创建出发任务", "可新建一条出发调度任务。"], ["edit_own_dispatch", "编辑自己的任务", "只可修改自己作为驾驶人的任务。"], ["submit_departure", "出发登记", "提交车辆出发登记并进入执行中。"], ["submit_transfer", "中转登记", "登记任务中转地点。"], ["submit_return", "返回登记", "登记返程路线、里程和车况。"], ["submit_photos", "上传任务照片", "上传出发或返程车辆照片。"], ["book_vehicle", "预约车辆", "发起车辆预约申请。"]] },
    { label: "任务访问", permissions: [["view_own_tasks", "查看自己的任务", "读取自己创建或作为驾驶人的任务。"], ["view_all_tasks", "查看全部任务", "读取所有调度任务和部门任务。"], ["edit_all_dispatch", "编辑全部任务", "修改其他人员的调度任务。"], ["approve_bookings", "审批车辆预约", "同意或拒绝车辆预约。"], ["delete_dispatch", "删除/取消任务", "删除任务或在无法删除时取消归档。"]] },
    { label: "车辆与车况", permissions: [["manage_vehicles", "车辆档案管理", "维护车辆基本资料、状态和档案。"], ["manage_vehicle_photos", "车辆照片管理", "上传和维护车辆原图及附件。"], ["manage_maintenance", "保养与保修", "记录保养、保修单和下次保养计划。"], ["refresh_tracker", "刷新 Tracker", "发起 Tracker 数据刷新。"]] },
    { label: "桌面与数据", permissions: [["desktop_console", "桌面调度台", "进入桌面调度台。"], ["view_history", "出行记录", "查看出行记录。"], ["view_tracker_history", "Tracker 历史", "查看车辆 Tracker 历史。"], ["sync_dispatch", "同步调度", "手动执行调度同步。"]] },
    { label: "系统管理", permissions: [["manage_photo_sync", "飞书照片同步", "连接拥有 Base 权限的管理员并同步车辆照片。"], ["manage_notifications", "部门通知设置", "编辑部门出发、返程和预约通知目标。"], ["manage_accounts", "账号权限管理", "编辑账号、角色、部门和权限。"]] }
  ];
  const t = (value) => state.language === "en" ? (texts[value] || value) : value;
  const esc = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
  const roleLabel = (role) => t(roleLabels[role] || role);
  const currentAccount = () => state.accounts.find((account) => account.id === state.selectedAccount) || null;
  const selectedPermissions = () => state.mode === "roles"
    ? new Set(Array.isArray(state.roles[state.selectedRole]) ? state.roles[state.selectedRole] : roleDefaults[state.selectedRole] || [])
    : new Set(currentAccount()?.permissions || []);
  const setNotice = (message, kind = "") => { const element = $("permissionNotice"); element.textContent = t(message); element.className = `account-status ${kind}`.trim(); };
  const renderRoleList = () => { const list = $("roleList"); list.innerHTML = Object.keys(roleLabels).map((role) => { const count = (state.roles[role] || roleDefaults[role] || []).length; return `<button type="button" class="role-list-item${state.selectedRole === role ? " is-selected" : ""}" data-role="${role}"><strong>${esc(roleLabel(role))}</strong><small>${count} ${esc(t("项权限"))}</small></button>`; }).join(""); };
  const renderAccountList = () => { const list = $("accountList"); list.innerHTML = state.accounts.length ? state.accounts.map((account) => `<button type="button" class="role-list-item${state.selectedAccount === account.id ? " is-selected" : ""}" data-account="${esc(account.id)}"><strong>${esc(account.displayName)}</strong><small>${esc(roleLabel(account.role))} · ${account.permissionMode === "custom" ? esc(t("已单独覆盖")) : esc(t("继承角色默认"))}</small></button>`).join("") : `<div class="empty-card">${esc(t("正在读取账号…"))}</div>`; };
  const renderMode = () => { $("roleList").hidden = state.mode !== "roles"; $("accountList").hidden = state.mode !== "accounts"; $("roleModeButton").className = `button ${state.mode === "roles" ? "button-primary" : "button-quiet"}`; $("accountModeButton").className = `button ${state.mode === "accounts" ? "button-primary" : "button-quiet"}`; };
  const renderEditor = () => {
    const role = state.selectedRole;
    const account = currentAccount();
    const selected = selectedPermissions();
    const hasTarget = state.mode === "roles" ? Boolean(role) : Boolean(account);
    $("editorTitle").textContent = state.mode === "roles" ? (role ? roleLabel(role) : t("选择一个角色")) : (account ? account.displayName : t("请选择左侧账号。"));
    $("editorHint").textContent = !hasTarget ? (state.mode === "roles" ? t("从左侧选择角色，编辑该角色的默认权限。") : t("请选择左侧账号。")) : state.mode === "roles" ? `${selected.size} ${t("项权限")} · ${t("修改后仅影响继承角色默认值的账号")}` : `${selected.size} ${t("项权限")} · ${account.permissionMode === "custom" ? t("该账号已覆盖角色默认权限") : t("该账号当前继承角色默认权限")}`;
    $("saveRoleButton").disabled = !hasTarget;
    $("saveRoleButton").textContent = t(state.mode === "roles" ? "保存角色权限" : "保存个人权限");
    $("resetRoleButton").hidden = !hasTarget;
    $("resetRoleButton").textContent = t(state.mode === "roles" ? "恢复系统默认" : "恢复角色默认");
    if (!hasTarget) { $("roleEditor").innerHTML = `<div class="empty-card">${esc(t(state.mode === "roles" ? "请选择左侧角色。" : "请选择左侧账号。"))}</div>`; return; }
    $("roleEditor").innerHTML = `<div class="permission-groups">${groups.map((group) => `<section class="permission-group"><h3>${esc(t(group.label))}</h3><div class="permission-check-list">${group.permissions.map(([value, label, description]) => `<label class="permission-check" title="${esc(t(description))}"><input type="checkbox" data-role-permission="${value}" ${selected.has(value) ? "checked" : ""} /><span><strong>${esc(t(label))}</strong><small>${esc(t(description))}</small></span></label>`).join("")}</div></section>`).join("")}</div>`;
  };
  const render = () => { renderMode(); renderRoleList(); renderAccountList(); renderEditor(); };
  const load = async () => { try { const [roleResponse, accountResponse] = await Promise.all([fetch("/api/auth/roles"), fetch("/api/auth/accounts")]); const rolePayload = await roleResponse.json(); const accountPayload = await accountResponse.json(); if (!roleResponse.ok) throw new Error(rolePayload.error || t("加载角色失败。")); if (!accountResponse.ok) throw new Error(accountPayload.error || t("加载角色失败。")); state.roles = rolePayload.roles || {}; state.accounts = accountPayload.accounts || []; const query = new URLSearchParams(location.search); const requestedRole = query.get("role"); const requestedAccount = query.get("account"); if (requestedAccount && state.accounts.some((account) => account.id === requestedAccount)) { state.mode = "accounts"; state.selectedAccount = requestedAccount; } else { state.selectedRole = roleLabels[requestedRole] ? requestedRole : state.selectedRole || "dispatcher"; } render(); } catch (error) { setNotice(error.message || t("加载角色失败。"), "error"); } };
  const saveRole = async () => {
    const target = state.mode === "roles" ? state.selectedRole : currentAccount()?.id;
    if (!target) return;
    const permissions = [...document.querySelectorAll("input[data-role-permission]:checked")].map((input) => input.dataset.rolePermission);
    const button = $("saveRoleButton"); button.disabled = true; setNotice("正在保存权限…");
    try { const endpoint = state.mode === "roles" ? `/api/auth/roles/${encodeURIComponent(target)}` : `/api/auth/accounts/${encodeURIComponent(target)}`; const response = await fetch(endpoint, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ permissions }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || t("保存失败。")); if (state.mode === "roles") state.roles[target] = payload.permissions || permissions; else { const index = state.accounts.findIndex((account) => account.id === target); if (index >= 0) state.accounts[index] = payload.account; } setNotice(state.mode === "roles" ? "角色权限已保存。" : "个人权限已保存。", "success"); render(); } catch (error) { setNotice(error.message || t("保存失败。"), "error"); } finally { button.disabled = false; }
  };
  const translate = () => { document.documentElement.lang = state.language === "en" ? "en" : "zh-CN"; document.title = `${t("权限管理")} · ${t("车辆调度控制台")}`; $("languageToggle").textContent = state.language === "en" ? "中文" : "English"; render(); };
  $("languageToggle").addEventListener("click", () => { state.language = state.language === "en" ? "zh" : "en"; sessionStorage.setItem("dispatch_language", state.language); translate(); });
  $("roleModeButton").addEventListener("click", () => { state.mode = "roles"; state.selectedRole = state.selectedRole || "dispatcher"; render(); });
  $("accountModeButton").addEventListener("click", () => { state.mode = "accounts"; state.selectedAccount = state.selectedAccount || state.accounts[0]?.id || ""; render(); });
  $("roleList").addEventListener("click", (event) => { const button = event.target.closest("button[data-role]"); if (!button) return; state.selectedRole = button.dataset.role; setNotice(""); render(); });
  $("accountList").addEventListener("click", (event) => { const button = event.target.closest("button[data-account]"); if (!button) return; state.selectedAccount = button.dataset.account; setNotice(""); render(); });
  $("saveRoleButton").addEventListener("click", saveRole);
  $("resetRoleButton").addEventListener("click", async () => {
    if (state.mode === "roles") { if (!state.selectedRole) return; state.roles[state.selectedRole] = [...roleDefaults[state.selectedRole]]; render(); setNotice("已恢复系统默认，请点击保存角色权限。", "success"); return; }
    const account = currentAccount(); if (!account) return;
    try { const response = await fetch(`/api/auth/accounts/${encodeURIComponent(account.id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resetPermissions: true }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || t("保存失败。")); const index = state.accounts.findIndex((item) => item.id === account.id); if (index >= 0) state.accounts[index] = payload.account; setNotice("个人权限已恢复为角色默认。", "success"); render(); } catch (error) { setNotice(error.message || t("保存失败。"), "error"); }
  });
  $("logoutButton").addEventListener("click", async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.replace("/admin-login"); });
  translate(); load();
})();
